from enum import Enum


class ThresholdStatus(str, Enum):
    UNDERSIZED = "UNDERSIZED"
    WITHIN_RANGE = "WITHIN_RANGE"
    OVERSIZED = "OVERSIZED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    INVALID = "INVALID"


class ReviewStatus(str, Enum):
    PROPOSED = "PROPOSED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class RejectionReason(str, Enum):
    ADMIN_BOUNDARY = "ADMIN_BOUNDARY"
    HARD_BARRIER = "HARD_BARRIER"
    DISCONNECTED = "DISCONNECTED"
    MAX_DWELLINGS = "MAX_DWELLINGS"
    MAX_AREA = "MAX_AREA"
